name: codecrew
description: A collaborative project matching platform

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.0
  http: ^1.1.0
  flutter_swiper_plus: ^2.0.4
  cached_network_image: ^3.2.3
  flutter_secure_storage: ^8.0.0
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  # fonts can be added here if needed